services:
  # --------------------------------------------------------------------------------------------------------------------
  # ORDER MYSQL
  # --------------------------------------------------------------------------------------------------------------------
  order-mysql:
    image: mysql:9.6.0
    restart: unless-stopped
    volumes:
      - order-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ORDER_SERVICE_MYSQL_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ORDER_SERVICE_MYSQL_DB_NAME}
      MYSQL_USER: ${ORDER_SERVICE_MYSQL_DB_USER}
      MYSQL_PASSWORD: ${ORDER_SERVICE_MYSQL_DB_PASSWORD}
    command: >
      --default-time-zone='+00:00'
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=${ORDER_SERVICE_MYSQL_INNODB_BUFFER_POOL_SIZE}
      --max-connections=${ORDER_SERVICE_MYSQL_MAX_CONNECTIONS}
    ports:
      - '${ORDER_SERVICE_MYSQL_DB_PORT}:3306'
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1.0"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h localhost -u $$MYSQL_USER -p$$MYSQL_PASSWORD -e \"SELECT 1 FROM information_schema.schemata WHERE schema_name='$$MYSQL_DATABASE'\"" ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
    networks:
      - mr-network

  # --------------------------------------------------------------------------------------------------------------------
  # ORDER SERVICE
  # --------------------------------------------------------------------------------------------------------------------
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:5
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    depends_on:
      order-mysql:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: ${ORDER_SERVICE_APPLICATION_NAME}
      SPRING_DATASOURCE_URL: jdbc:mysql://${ORDER_SERVICE_MYSQL_DB_HOST}:3306/${ORDER_SERVICE_MYSQL_DB_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${ORDER_SERVICE_MYSQL_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${ORDER_SERVICE_MYSQL_DB_PASSWORD}
      SERVER_PORT: ${ORDER_SERVICE_PORT}
      INTEGRATION_PAYMENT_SERVICE_URL: ${INTEGRATION_PAYMENT_SERVICE_URL}
      INTEGRATION_INVOICE_SERVICE_URL: ${INTEGRATION_INVOICE_SERVICE_URL}
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: "1.0"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    networks:
      - mr-network


volumes:
  order-mysql:

networks:
  mr-network: